<script src="{{ asset('principal/js/jquery/jquery-2.2.4.min.js') }}"></script>
<!-- Popper js -->
<script src="{{ asset('principal/js/popper.min.js') }}"></script>
<!-- Bootstrap js -->
<script src="{{ asset('principal/js/bootstrap.min.js') }}"></script>
<!-- Plugins js -->
<script src="{{ asset('principal/js/plugins.js') }}"></script>
<!-- Active js -->
<script src="{{ asset('principal/js/active.js') }}"></script>
